prettier/eslint-config-prettier

- cli.js
Without the `'use strict';` Node.js v4.x will choke on let/const
> add "use strict" for node.js v4 support

- index.js
one-var-declaration-per-line causes this error when use with eslint-plugin-prettier:
```
#:#  error  Follow `prettier` formatting (expected ' ' but found '\n')  prettier/prettier
```
with this code:
```
var a = 'a', 
b = 'b';
```
> Add one-var-declaration-per-line to disabled rules

- README.md
I propose the grammar of the description is changed to be less ambiguous. (I initially read it as: it could be potentially conflict if Prettier is turned off.)
If this PR is merged, the change would need to be reflected in the repo description, too.
> Grammar change on description

- index.js
Hi Simon,
The [template-tag-spacing](http://eslint.org/docs/rules/template-tag-spacing) rule is already handled by prettier as you can see:  https://prettier.github.io/prettier/#%7B%22content%22%3A%22func%60Hello%20world%60%3B%5Cnfunc%20%60Hello%20world%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
> Turn "template-tag-spacing" off

- index.js
New rule indent-legacy introduced in v4 functions similarly to indent. Conflicts with prettier.
> Turn off indent-legacy

- index.js
- package.json
- yarn.lock
Turn off [function-paren-newline](https://eslint.org/docs/rules/function-paren-newline) and upgrade to ESLint 4.6.0.
> Turn off function-paren-newline, introduced in ESLint v4.6.0

- README.md
- bin/validators.js
- index.js
- test/cli.js
- test/validators.js
Prettier will remove lines above comments. This fails with the default settings used in a Preact CLI app where `'lines-around-comment': 2,` is included in the eslint configuration.
> Prettier cares about lines-around-comment

- README.md
- index.js
- test/cli.js
This disables the eslint rule `no-unexpected-multiline` which is part of the recommended eslint config. Additionally, as suggested by @lydell, it is marked as a special case.
Closes #32.
> Disable no-unexpected-multiline, document as special case

- package.json
- test/helpers/get-env.js
- test/lint-verify-fail.js
- test/rules.js
This fixes the tests failing on windows. I also tweaked the script for `test:cli-sanity` because it was causing this issue:
```
λ yarn test
yarn run v1.2.1
$ npm run test:lint && npm run test:ava && npm run test:cli-sanity
> eslint-config-prettier@2.7.0 test:lint E:\Projects\repos\eslint-config-prettier
> eslint .
> eslint-config-prettier@2.7.0 test:ava E:\Projects\repos\eslint-config-prettier
> ava
26 passed
> eslint-config-prettier@2.7.0 test:cli-sanity E:\Projects\repos\eslint-config-prettier
> eslint --print-config .eslintrc.js | ./bin/cli.js
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! eslint-config-prettier@2.7.0 test:cli-sanity: `eslint --print-config .eslintrc.js | ./bin/cli.js`
npm …
```
> Fix tests, script failing on windows

- package-lock.json
- package.json
- vue.js
This PR updates `eslint-plugin-vue`, as well as updates `vue` config, by using brand new `vue/no-layout-rules` config, that is automatically generated based on the `type` property in rules' metadata. This way we won't get out-of-sync :)
> chore(vue): Use dedicated vue/no-layout-rules config

- .eslintrc.base.js
- README.md
- babel.js
- package-lock.json
- package.json
- test-lint/babel.js
I'm not aware of any popular ESLint configs that use it so I just left it out of the configuration example for the sake of simplicity, but I think it's visible enough that people will notice that it exists.
Fixes #67.
> Add support for eslint-plugin-babel

- @typescript-eslint.js
- package-lock.json
- package.json
- updated `@typescript-eslint`
- disabled new rule `@typescript-eslint/no-extra-parens` (conflict originally found by @jgorfine)
> chores on @typescript-eslint

- package-lock.json
- package.json
- react.js
The `react/jsx-curly-newline` rule was introduced by `eslint-plugin-react@7.14.0`.
See also:
- https://github.com/yannickcr/eslint-plugin-react/blob/v7.14.2/CHANGELOG.md#7140---2019-06-23
- https://github.com/yannickcr/eslint-plugin-react/blob/v7.14.2/docs/rules/jsx-curly-newline.md
Fix #96
> Turn off `react/jsx-curly-newline`

- @typescript-eslint.js
- README.md
- package-lock.json
- package.json
The new rule `@typescript-eslint/quotes` has been added since `@typescript-eslint@2.1.0`.
See <https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/quotes.md>
- Update `@typescript-eslint/eslint-plugin` from 2.0.0 to 2.1.0
- Add the rule link to the "quotes" section in README.
Fix #104
> Disable `@typescript-eslint/quotes` rule

- @typescript-eslint.js
- README.md
- package-lock.json
- package.json
The new rule `@typescript-eslint/brace-style` has been added since `@typescript-eslint/eslint-plugin@2.2.0`.
See also:
- https://github.com/typescript-eslint/typescript-eslint/pull/810
- https://github.com/typescript-eslint/typescript-eslint/blob/v2.2.0/packages/eslint-plugin/docs/rules/brace-style.md
> Disable `@typescript-eslint/brace-style` rule

- @typescript-eslint.js
- README.md
- package-lock.json
- package.json
The new rule `@typescript-eslint/space-before-function-paren` has been added since `@typescript-eslint/eslint-plugin@2.8.0`.
- https://github.com/typescript-eslint/typescript-eslint/blob/v2.8.0/packages/eslint-plugin/docs/rules/space-before-function-paren.md
- https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.8.0
- https://github.com/typescript-eslint/typescript-eslint/pull/924
This rule is an extension of the ESLint core rule [`space-before-function-paren`](https://eslint.org/docs/rules/space-before-function-paren),
and `eslint-config-prettier` has disabled the rule already.
- https://github.com/prettier/eslint-config-prettier/blob/ed97c2f4cb77b5cc8cb941900b81304b5cd6eb1d/index.js#L77
> Disable `@typescript-eslint/space-before-function-paren` rule

- @typescript-eslint.js
- README.md
- package-lock.json
- package.json
The new rule `@typescript-eslint/no-extra-semi` has been added since `@typescript-eslint/eslint-plugin@2.13.0`.
- https://github.com/typescript-eslint/typescript-eslint/blob/v2.13.0/packages/eslint-plugin/docs/rules/no-extra-semi.md
- https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.13.0
- typescript-eslint/typescript-eslint#1237
This rule is an extension of the ESLint core rule `no-extra-semi`,
and `eslint-config-prettier` has disabled the rule already.
- https://github.com/prettier/eslint-config-prettier/blob/dcca556e260af985ece4d9af92531fa649268f80/index.js#L52
> Disable @typescript-eslint/no-extra-semi

- README.md
- package-lock.json
- package.json
- vue.js
The new rule `vue/max-len` has been added since `eslint-plugin-vue@6.1.0`.
- https://eslint.vuejs.org/rules/max-len.html
- https://github.com/vuejs/eslint-plugin-vue/releases/tag/v6.1.0
- https://github.com/vuejs/eslint-plugin-vue/pull/959
This rule is an extension of the ESLint core rule `max-len`,
and `eslint-config-prettier` has disabled the rule already by setting value to `0`.
- https://github.com/prettier/eslint-config-prettier/blob/d6bf4c063dfaf1de0b5c22ba0156184955b39b44/index.js#L14
> Disable vue/max-len

- @typescript-eslint.js
- README.md
- package-lock.json
- package.json
- test-lint/@typescript-eslint.ts
> Turn off `@typescript-eslint/comma-dangle`

- @typescript-eslint.js
- README.md
- package-lock.json
- package.json
TypeScript ESLint v4.6.0 has added a new rule: `@typescript-eslint/space-infix-ops`.
This rule is an extension of the core rule `space-infix-ops` that `eslint-config-prettier` has turned off already.
See also:
- https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.6.0
- https://github.com/typescript-eslint/typescript-eslint/blob/v4.6.0/packages/eslint-plugin/docs/rules/space-infix-ops.md
- https://github.com/prettier/eslint-config-prettier/blob/v6.14.0/index.js#L82
> Turn off `@typescript-eslint/space-infix-ops`

- package-lock.json
- package.json
- test-lint/unicorn.js
- unicorn.js
[`unicorn/empty-brace-spaces` added in `eslint-plugin-unicorn@24.0.0`](https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v24.0.0)
Prettier put line break in several cases, `unicorn/empty-brace-spaces` don't allow.
> Disable `unicorn/empty-brace-spaces`

- README.md
`README.md` says to add eslint-config-prettier to your `.eslintrc.*` file, but it's supposed to be `"prettier"` as far as I can tell. The code example also shows `"prettier"` instead of `"eslint-config-prettier"` on the very next line. A little confusing, but easily fixable 😄
> Clarify what to add to .eslintrc in readme

- .github/workflows/check.yml
- .github/workflows/test.yml
Bumps GitHub Actions to their latest major versions. Main change is they're now using Node 16 instead of 12, which was EOL at end of April.
- Releases for `actions/cache` can be [found here](https://github.com/actions/cache/releases)
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
> ci: bump github actions

- .github/workflows/check.yml
- .github/workflows/test.yml
This PR:
-   Removes Git credentials/SSH keys after checkout as a security precaution by setting `persist-credentials` to false, they are not used after the initial checkout
- Declares the minimum permissions for CI workflows to run at the workflow level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
> ci: harden workflows

- README.md
- index.js
Move many rules to deprecated section:
- [`generator-star`](https://eslint.org/docs/latest/rules/generator-star): _This rule was removed in ESLint v1.0 and replaced by the [generator-star-spacing](https://eslint.org/docs/latest/rules/generator-star-spacing) rule._
- [`no-arrow-condition`](https://eslint.org/docs/latest/rules/no-arrow-condition): _This rule was removed in ESLint v2.0 and replaced by a combination of the [no-confusing-arrow](https://eslint.org/docs/latest/rules/no-confusing-arrow) and [no-constant-condition](https://eslint.org/docs/latest/rules/no-constant-condition) rules._
- [`no-comma-dangle`](https://eslint.org/docs/latest/rules/no-comma-dangle): _This rule was removed in ESLint v1.0 and replaced by the [comma-dangle](https://eslint.org/docs/latest/rules/comma-dangle) …
> Move removed rules to deprecated section

- index.js
Prettier does not add/remove BOM from files afaict, so this rule should not be disabled.
Related:
https://github.com/prettier/prettier/issues/6461
> Do not disable unicode-bom

- README.md
- bin/validators.js
- index.js
- package-lock.json
- test/cli.test.js
- test/validators.test.js
It conflicts with Prettier's template indenting
> turn off `unicorn/template-indent`

- .changeset/six-dolls-itch.md
- package.json
[Node 21.1.0 added a flag to detect module types](https://github.com/nodejs/node/releases/tag/v21.1.0) that became enabled by [default in Node 22.7.0](https://nodejs.org/api/packages.html#syntax-detection).
Declaring the type will cause Node to skip detection on startup, reducing startup time.
Declaring the package type is also considered good practice according to https://nodejs.org/api/modules.html#enabling.
> chore(package): explicitly declare js module type

- .changeset/angry-kangaroos-sleep.md
- README.md
- flat.d.ts
- flat.js
- index.d.ts
- index.js
- package.json
> fix: separate the `/flat` entry for compatibility

- .changeset/purple-ravens-pump.md
- package.json
The addition of the [`homepage`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#homepage) property allows for the URL to the repo to be correctly displayed when hovered over in VS Code when using a proxy registry like in Azure DevOps:
Compared to something like eslint-plugin-regexp, which [does have the homepage set](https://github.com/ota-meshi/eslint-plugin-regexp/blob/2d90a1aca863508647115c76a7b0c23b493eb0e0/package.json#L60):
> chore(package): add homepage url
